# -*- coding: utf-8 -*-
"""[6]ARCH估計.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZfUexOnCsbl1NLNiCN5spH724Ic3eLYR
"""

# 安裝套件
!pip install arch

# 三大套件
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 資料下載套件
import ffn

# arch套件
from arch import arch_model

#下載資料
data = ffn.get('^gspc',start='2020-01-01')
# 計算報酬率
data['ret'] = np.log(data.gspc).diff()
# 檢查
data.head()







# 將報酬率放入arch_model(指定garch)
am = arch_model(data.ret.dropna(),garch,p=1,q=1)
res = am.fit()
print(res.summary())

# 估計每日條件波動率
res.conditional_volatility

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

res.conditional_volatility.plot()

# FIGARCH

res = arch_model(data.ret.dropna()).fit()
print(res.summary)

res.conditional_volatility



